#!/bin/bash
IFS=

echo \* \`$(date "+%H:%M")\` - $(basename `git rev-parse --show-toplevel`) [$(git rev-parse --abbrev-ref HEAD)] $(git log -1 --format=format:"\`%h\` %s") >> ~/Documents/wiki/diary/$(date "+%Y-%m-%d").md
