#!/bin/bash
IFS=

echo - \`$(date "+%H:%M")\` - \`$(basename `git rev-parse --show-toplevel`):$(git rev-parse --abbrev-ref HEAD)\` $(git log -1 --format=format:"\`%h\` %s") >> ~/Dropbox/wiki/diary/$(date "+%Y-%m-%d").md
# Run ctags async
.git/hooks/ctags >/dev/null 2>&1 &
