#!/bin/bash
IFS=

# BODY=$(git log -1 --format=format:"%b" | awk 'NF' | awk '{print "    - " $0}')

echo \* \`$(date "+%H:%M")\` - $(basename `git rev-parse --show-toplevel`) [$(git rev-parse --abbrev-ref HEAD)] $(git log -1 --format=format:"\`%h\` %s") >> ~/Documents/wiki/diary/$(date "+%Y-%m-%d").wiki
# echo $BODY >> ~/Documents/wiki/diary/$(date "+%Y-%m-%d").wiki
